//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Population.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NGJBJM5\\SQLEXPRESS;Initial Catalog=\"C:\\USERS\\TONY\\DOCUMENTS\\B" +
            "OOKS\\C#\\STUDENT SAMPLE PROGRAMS\\CHAP11\\POPULATIONDB.MDF\";Integrated Security=Tru" +
            "e")]
        public string C__USERS_TONY_DOCUMENTS_BOOKS_C__STUDENT_SAMPLE_PROGRAMS_CHAP11_POPULATIONDB_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_TONY_DOCUMENTS_BOOKS_C__STUDENT_SAMPLE_PROGRAMS_CHAP11_POPULATIONDB_MDFC" +
                    "onnectionString"]));
            }
        }
    }
}
